spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1000
      max-lifetime: 15000
      idle-timeout: 10000
      auto-commit: false
      minimum-idle: 10
      connectionTimeout: 20000
      leak-detection-threshold: 5000

  redis:
    host: 127.0.0.1
    port: 6379

feign:
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      feignName: # @FeignClient에서 name 값, 전역으로 설정하려면 default
        loggerLevel: BASIC #full
        # feign의 전역 timeout 설정 : 5초
        connectTimeout: 5000
        readTimeout: 5000
  target-api:
    coupon: http://10.100.154.54:10888
